'use strict';
import { resolve } from 'path';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import packageJson from '../package.json';

const UNKNOWN = 'unknown';

const rootdir = resolve(__dirname, '..');
const nodeModulesDir = resolve(rootdir, 'node_modules');

const deps: Deps.Modules = packageJson.dependencies || {};
const depsKeys = Object.keys(deps);
const peerDeps: Deps.Modules = packageJson.peerDependencies || {};
const peerDepsKeys = Object.keys(peerDeps);

const result = [
  '# LICENSES\n',
  
  'This file is auto-generated by `bun ./.bun/license-checkerts`.\n',

  '## Index\n',

  '- [Dependencies](#dependencies)',
  ...(depsKeys.map(genIndex)),
  '- [peerDependencies](#peerdependencies)',
  ...(peerDepsKeys.map(genIndex)),

  '## Dependencies\n',

  ...(genLicenses(depsKeys)),

  '## peerDependencies\n',

  ...(genLicenses(peerDepsKeys)),
].join('\n');

const outfile = resolve(rootdir, 'LICENSES.md');

writeFileSync(outfile, result, 'utf8');

function genIndex (name: string): string {
  const link = name
    .toLowerCase()
    .replace(/(\s)/g, '-')
    .replace(/(@|\/)/g, '');

  return `  - [${name}](#user-content-${encodeURIComponent(link)})`;
};

function genLicenses (keys: string[]): string[] {
  const depsData: Deps.Data[] = keys.map(getDependenciesData);

  const rows: string[] = depsData
    .map(processDependencies)
    .reduce((rows, lRows) => ([...rows, ...lRows]), [] as string[]);

  return rows;
};

function getDependenciesData (name: string): Deps.Data {
  const moduleDir = resolve(nodeModulesDir, name);
  const packageJsonPath = resolve(moduleDir, 'package.json');
  const packageData = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
  const licenseFileCandidates = ['LICENSE', 'LICENSE.md', 'LICENSE.txt'];
  const licensePath = licenseFileCandidates
    .map((f) => resolve(moduleDir, f))
    .find((p) => existsSync(p));

  const licenseName = name as Deps.DataName;

  const version = (packageData.version || UNKNOWN) as Deps.DataVersion;

  const licenseType = (packageData.license || packageData.licenses?.[0]?.type || UNKNOWN) as Deps.DataLicenseType;

  const licenseContent = (licensePath && existsSync(licensePath)
    ? readFileSync(licensePath, 'utf8')
    : undefined) as Deps.DataLicenseContent | undefined;

  const data: Deps.Data = {
    name: licenseName,
    version,
    licenseType,
    licenseContent,
  };

  return data;
};

function processDependencies (deps: Deps.Data): string[] {
  const {
    name,
    version,
    licenseType,
    licenseContent,
  } = deps;

  const titleRow = `### ${name}`;

  const versionBadge = version === UNKNOWN
    ? `<img src="https://img.shields.io/badge/version-unknown-lightgrey" alt="version unknown">`
    : `<img src="https://img.shields.io/badge/version-${version}-blue" alt="version ${version}">`;

  const licenseBadge = licenseType === UNKNOWN
    ? `<img src="https://img.shields.io/badge/license-unknown-lightgrey" alt="license unknown">`
    : `<img src="https://img.shields.io/badge/license-${fixLicenseTypeForURL(licenseType)}-blue" alt="license ${licenseType}">`;

  const rows = [
    titleRow,
    `<div style="display: flex;">${versionBadge} ${licenseBadge}</div>`,
    '',
  ];

  if (!licenseContent) return rows;

  return [
    ...rows,
    '#### License Content',
    '',
    '```',
    licenseContent,
    '```',
    '',
  ];
};

function fixLicenseTypeForURL (licenseType: string): string {
  return licenseType
    .replace(/\s/g, '&space;')
    .replace(/_/g, '&underscore;')
    .replace(/-/g, '&hyphen;')
    .replace(/&space;/g, '_')
    .replace(/&underscore;/g, '__')
    .replace(/&hyphen;/g, '--');
};

namespace Deps {
  export type Modules = Record<string, string>;

  export type Data = {
    name: DataName;
    version: DataVersion;
    licenseType: DataLicenseType;
    licenseContent?: DataLicenseContent;
  };

  export type DataName = Brand<string, 'Deps.DataName'>;
  export type DataVersion = Brand<string, 'Deps.DataVersion'>;
  export type DataLicenseType = Brand<string, 'Deps.DataLicenseType'>;
  export type DataLicenseContent = Brand<string, 'Deps.DataLicenseContent'>;
};

type Brand<K, T> = K & { __brand: T };
