'use strict';

import {
  MaiBreadcrumbItem,
  MaiBreadcrumbs,
  MaiButton,
  MaiCard,
  MaiCardBody,
  MaiCardFooter,
  MaiCardHeader,
  MaiCodeBlock,
  MaiCodeBlockStyleProvider,
  MaiH1,
  MaiH2,
  MaiH3,
  MaiH4,
  MaiH5,
  MaiH6,
  MaiHeadings,
  MaiHeadingsStyleProvider,
  MaiMarkdown,
  MaiModal,
  MaiModalBody,
  MaiModalContent,
  MaiModalFooter,
  MaiModalHeader,
  MaiLink,
  MaiPagination,
  MaiSkeleton,
  MaiSNSLink,
  useDisclosure,
  useDraggable,
} from './components';

import {
  maiFonts,
  MaiUIProvider,
} from './core';

import {
  MaiArticleContainer,
  MaiArticleDateInfo,
  MaiArticleDivider,
  MaiArticleLayout,
  MaiArticleThumbnail,
} from './layouts';

import {
  useTheme,
} from './features/theme';

export * from './types/mai-ui';

export {
  maiFonts,
  useDisclosure,
  useDraggable,
  useTheme,
  MaiArticleContainer,
  MaiArticleDateInfo,
  MaiArticleDivider,
  MaiArticleLayout,
  MaiArticleThumbnail,
  MaiBreadcrumbItem,
  MaiBreadcrumbs,
  MaiButton,
  MaiCard,
  MaiCardBody,
  MaiCardFooter,
  MaiCardHeader,
  MaiCodeBlock,
  MaiCodeBlockStyleProvider,
  MaiH1,
  MaiH2,
  MaiH3,
  MaiH4,
  MaiH5,
  MaiH6,
  MaiHeadings,
  MaiHeadingsStyleProvider,
  MaiMarkdown,
  MaiModal,
  MaiModalBody,
  MaiModalContent,
  MaiModalFooter,
  MaiModalHeader,
  MaiLink,
  MaiPagination,
  MaiSkeleton,
  MaiSNSLink,
  MaiUIProvider,
};

const MaiUI = {
  fonts: maiFonts,
  useDisclosure,
  useDraggable,
  useTheme,
  ArticleContainer: MaiArticleContainer,
  ArticleDateInfo: MaiArticleDateInfo,
  ArticleDivider: MaiArticleDivider,
  ArticleLayout: MaiArticleLayout,
  ArticleThumbnail: MaiArticleThumbnail,
  BreadcrumbItem: MaiBreadcrumbItem,
  Breadcrumbs: MaiBreadcrumbs,
  Button: MaiButton,
  Card: MaiCard,
  CardBody: MaiCardBody,
  CardFooter: MaiCardFooter,
  CardHeader: MaiCardHeader,
  CodeBlock: MaiCodeBlock,
  CodeBlockStyleProvider: MaiCodeBlockStyleProvider,
  H1: MaiH1,
  H2: MaiH2,
  H3: MaiH3,
  H4: MaiH4,
  H5: MaiH5,
  H6: MaiH6,
  Markdown: MaiMarkdown,
  Headings: MaiHeadings,
  HeadingsStyleProvider: MaiHeadingsStyleProvider,
  Modal: MaiModal,
  ModalBody: MaiModal,
  ModalContent: MaiModalContent,
  ModalFooter: MaiModalFooter,
  ModalHeader: MaiModalHeader,
  Link: MaiLink,
  Pagination: MaiPagination,
  Provider: MaiUIProvider,
  Skeleton: MaiSkeleton,
  SNSLink: MaiSNSLink,
};

export default MaiUI;
